steps:
- checkout: self
  submodules: true
  fetchDepth: 2

- bash: |
    echo $PWD
    git log
  displayName: 'Root'

- bash: |
    cd ./module-b
    echo $PWD
    git log
  displayName: 'Submodule'

- bash: |
    cd ./module-b/module-c
    echo $PWD
    git log
  displayName: 'Submodule of submodule'
